In [2]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [21, 22, 23, 24, 25],
    "Score": [88, 76, 90, 85, 92]
}, index=[10, 20, 30, 40, 50])

In [3]:
data.iloc[:, [0, 2]]

   Name  Score
10    A     88
20    B     76
30    C     90
40    D     85
50    E     92

In [4]:
data.iloc[1, [0]]

Name    B
Name: 20, dtype: object

In [5]:
data.iloc[[-1, -2]]

   Name  Age  Score
50    E   25     92
40    D   24     85

In [6]:
data.loc[30]

Name      C
Age      23
Score    90
Name: 30, dtype: object

In [7]:
data.iloc[2]

Name      C
Age      23
Score    90
Name: 30, dtype: object

In [8]:
data.loc[[20, 50]]

   Name  Age  Score
20    B   22     76
50    E   25     92

In [9]:
data.iloc[[1, 4]]

   Name  Age  Score
20    B   22     76
50    E   25     92

In [10]:
data.iloc[1:4]

   Name  Age  Score
20    B   22     76
30    C   23     90
40    D   24     85

In [11]:
data.loc[20:40]

   Name  Age  Score
20    B   22     76
30    C   23     90
40    D   24     85

In [12]:
deliveriesData = pd.read_csv('deliveries.csv')
matchesData = pd.read_csv('matches.csv')
deliveriesData.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [13]:
#Q2 Total extras conceded by each bowling team
bowlingTeam = deliveriesData.groupby('bowling_team')
bowlingTeam['extra_runs'].count().sort_values(ascending=False).head(10)

bowling_team
Mumbai Indians                 18879
Royal Challengers Bangalore    17920
Kolkata Knight Riders          17411
Kings XI Punjab                17392
Delhi Daredevils               17099
Chennai Super Kings            15562
Rajasthan Royals               14111
Deccan Chargers                 9039
Sunrisers Hyderabad             8888
Pune Warriors                   5457
Name: extra_runs, dtype: int64

In [14]:
#Q3 Batsman with the most fours hit
batsmanRuns = deliveriesData['batsman_runs'] == 4
newMask = deliveriesData[batsmanRuns]
newMask.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(5)

batsman
G Gambhir    484
SK Raina     402
DA Warner    401
S Dhawan     401
V Kohli      384
Name: batsman_runs, dtype: int64

In [15]:
#Q4 Bowlers who have bowled the most no-balls
bolwerMask = deliveriesData['noball_runs'] > 0
mostNoBalls = deliveriesData[bolwerMask]
mostNoBalls.groupby('bowler')['noball_runs'].sum().sort_values(ascending=False).head(5)

bowler
S Sreesanth    27
I Sharma       21
A Mishra       20
JA Morkel      18
SL Malinga     18
Name: noball_runs, dtype: int64

In [16]:
#Q5 For batsman 'V Kohli', how many legal deliveries (where ball == 1 in the over) has he faced?
legal_kohli = deliveriesData[(deliveriesData['batsman'] == 'V Kohli') & (deliveriesData['wide_runs'] == 0) & (deliveriesData['noball_runs'] == 0)]
balls_faced = len(legal_kohli)          # or legal_kohli.shape[0]
print(balls_faced)

3394

In [17]:
# isin
#Find the top 5 bowlers who have the best (lowest) average in death overs
#(overs 16–20), but only consider bowlers who have bowled at least 30 legal deliveries in death overs.
filter_bowler = deliveriesData['bowler']
death_delivery = filter_bowler[(deliveriesData['over'] >= 16)]
bowler_mask = deliveriesData[death_delivery['noball_runs'] == 0]

KeyError: 'noball_runs'

In [19]:
data1 = {
    "date": [
        "2024-01-01","2024-01-01","2024-01-01","2024-01-01",
        "2024-01-02","2024-01-02","2024-01-02","2024-01-02",
        "2024-01-03","2024-01-03","2024-01-03","2024-01-03"
    ],
    "product": [
        "Laptop","Laptop","Phone","Phone",
        "Laptop","Laptop","Phone","Phone",
        "Laptop","Laptop","Phone","Phone"
    ],
    "region": [
        "East","West","East","West",
        "East","West","East","West",
        "East","West","East","West"
    ],
    "sales": [1200, 1500, 800, 900, 1300, 1400, 850, 950, 1250, 1600, 900, 1000],
    "units_sold": [3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6]
}

df = pd.DataFrame(data1)
df["date"] = pd.to_datetime(df["date"])
df

         date product region  sales  units_sold
0  2024-01-01  Laptop   East   1200           3
1  2024-01-01  Laptop   West   1500           4
2  2024-01-01   Phone   East    800           5
3  2024-01-01   Phone   West    900           6
4  2024-01-02  Laptop   East   1300           3
5  2024-01-02  Laptop   West   1400           4
6  2024-01-02   Phone   East    850           5
7  2024-01-02   Phone   West    950           6
8  2024-01-03  Laptop   East   1250           3
9  2024-01-03  Laptop   West   1600           4
10 2024-01-03   Phone   East    900           5
11 2024-01-03   Phone   West   1000           6

In [22]:
pd.pivot_table(df, index = 'product', columns = 'region', values = 'sales', aggfunc = 'sum')

region   East  West
product
Laptop   3750  4500
Phone    2550  2850

In [23]:
pd.pivot_table(df, index = 'product', columns = 'date', values = 'sales', aggfunc = 'sum')

date     2024-01-01  2024-01-02  2024-01-03
product
Laptop         2700        2700        2850
Phone          1700        1800        1900

In [24]:
pd.pivot_table(df, index = 'date', columns = 'region', values = 'sales', aggfunc = 'sum')

region      East  West
date
2024-01-01  2000  2400
2024-01-02  2150  2350
2024-01-03  2150  2600

In [27]:
pd.pivot_table(df, index = 'product', columns = 'region', values = 'sales', aggfunc = 'mean')

region     East    West
product
Laptop   1250.0  1500.0
Phone     850.0   950.0

In [30]:
pd.pivot_table(df, index = 'product', columns = 'region', values = ['sales', 'units_sold'], aggfunc = 'sum')

        sales       units_sold
region   East  West       East West
product
Laptop   3750  4500          9   12
Phone    2550  2850         15   18

In [34]:
pd.pivot_table(df, index = 'product', columns = 'region', values = 'date')

region        East       West
product
Laptop  2024-01-02 2024-01-02
Phone   2024-01-02 2024-01-02